#!/usr/bin/ksh

#
# CDDL HEADER START
#
# The contents of this file are subject to the terms of the
# Common Development and Distribution License (the "License").
# You may not use this file except in compliance with the License.
#
# You can obtain a copy of the license at usr/src/OPENSOLARIS.LICENSE
# or http://www.opensolaris.org/os/licensing.
# See the License for the specific language governing permissions
# and limitations under the License.
#
# When distributing Covered Code, include this CDDL HEADER in each
# file and include the License file at usr/src/OPENSOLARIS.LICENSE.
# If applicable, add the following below this CDDL HEADER, with the
# fields enclosed by brackets "[]" replaced with your own identifying
# information: Portions Copyright [yyyy] [name of copyright owner]
#
# CDDL HEADER END
#

. /lib/svc/share/smf_include.sh

if [ -z $SMF_FMRI ]; then
    echo "Error: SMF framework variables are not initialized"
    exit $SMF_EXIT_ERR
fi

case "$1" in
start)
    cd /opt/rundeck
    /opt/local/bin/java -Xmx2048m -Xms1024m -jar -server -Drundeck.jetty.connector.forwarded=true ./rundeck-@VER@.war &
    ;;
*)
    print "Usage: $0 {start}"
    exit 1
    ;;
esac
